spring.application.name=portfolio-services

spring.jackson.time-zone=Asia/Kolkata

app.cors.allowed-origins=http://localhost:3000,https://www.kumarrahul.in,https://kumarrahul.in
app.exchange-rate.api-key=2b7d7205e37e8f77e99adbb2
app.exchange-rate.base-url=https://v6.exchangerate-api.com/v6

# Spring Data Source Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
